### PR TITLE
 fix for reading data from configuration image

### PR DESCRIPTION
**Pull request by arturobrzut**
Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51822
   fix in repo https://github.ibm.com/IBMPrivateCloud/bedrock-shim/pull/113
                https://github.com/IBM/ibm-common-service-operator/pull/738
Solution:
- [x] - create bedrock shim image with xpkg data in bedrock shim repo
- [X] - create configmap in operator
- [x] - attach data from bedrock-shim to configmap
- [x] - attach configmap to pod
- [x] - test pod if read confifuration from file
- [x] - test if init container tag was change to digest by CICD

**Should work with this Configuration CR**
we need to update it in Common Service installer 
```
apiVersion: pkg.ibm.crossplane.io/v1
kind: Configuration
metadata:
  labels:
    ibm-crossplane-provider: odlm
  name: ibm-crossplane-bedrock-shim-config
spec:
  ignoreCrossplaneConstraints: false
  package: ibm-crossplane-bedrock-shim-config
  packagePullPolicy: Never
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false

```

how to test before merge:
1. Prepare bedrock shim image with xpkg files inside image
2. Install Crossplane from strach -> Do not create CR Configuration 
3. Create Configmap , YAML from this PR
4. Update CSV as in this PR
5. Create Configuration CR with 
```
  package: ibm-crossplane-bedrock-shim-config
  packagePullPolicy: Never
```
6. Check if we can create KafkaClaim

### CODE REVIEW

**Comment by arturobrzut** [comment]
@pgodowski logs in initcontainer
image

**Comment by arturobrzut** [comment]
xpkg file contains number at the end which we can not change.
This xpkg file we have to put in configuration CR which is deploy by common services installer, to prevent updating each time installer,
we can set in CR xpkg file without this number and create two caches one with number and one without. After that crossplane start without issue.

**Comment by ppyt-pl** [comment]
After applying the changes to CSV and creating configMap, Crossplane pod is restarted, initcontainer does its job with copying and we can see package files in `cache/`. Next, after creating `Configuration` we can see that it is unpacked and we see all Compositions 
image

**Review by PawelKopel — APPROVED** [review]

**Review by ppyt-pl — APPROVED** [review]
ok

**Pull request merged**
